[project]
name = "optikit-examples"
version = "0.1.0"
description = "Scripts to support CI checks on examples"
readme = "README.md"
requires-python = "==3.13.13"
dependencies = [
    "build123d>=0.13.0",
    "deepmerge>=3.0.1",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = ["poethepoet>=0.48.0"]

[tool.poe.tasks]
assemble.script = "tools.examples.cad.assemble:main_file"
assemble-batch.script = "tools.examples.cad.assemble:main_batch"
convert.script = "tools.examples.cad.convert:main_detect"
convert-batch.script = "tools.examples.cad.convert:main_batch"
config.script = "tools.examples.newswitch.config:main_file"
