devices:
  bigcamera42:
    device_id: bigcamera42
    manufacturer: HIK ROBOTICS
    name: MV-CA023-10UM
    pixelcount:
      binning: 1
      channels: 1
      exposure_time_ms:
        increment: 0.001
        max: 10000.0
        min: 0.024
        value: 25.0
      framerate_per_sec:
        max: 163.0
        min: 0.5
        value: 163.0
      gain_db:
        increment: 0.01
        max: 23.98
        min: 0.0
        value: 0.0
      pixelpitch_um:
        x: 10.0
      trigger:
        edge: rising
        type: hardware
      x: 1920
      y: 1200
    tags:
    - monochrome
    - global-shutter
    - gige
    type: camera
  hotlaser123:
    controller: my-favorite-mainboard
    device_id: hotlaser123
    manufacturer: Boison
    max_power_mw: 100.0
    modulation: digital
    name: boison-488
    shutter: false
    type: laser
    wavelength_nm: 485
  just-some-boring-stage:
    axes:
    - inverted: false
      label: x
      steps_per_um: 8.0
      travel_um: 100000.0
    - inverted: false
      label: y
      steps_per_um: 8.0
      travel_um: 100000.0
    - inverted: true
      label: z
      steps_per_um: 25.0
      travel_um: 10000.0
    controller: my-favorite-mainboard
    device_id: just-some-boring-stage
    homing_required: true
    manufacturer: openUC2
    max_speed_um_per_sec: 5000.0
    name: xyz-linear-100
    type: stage
  my-favorite-mainboard:
    device_id: my-favorite-mainboard
    firmware:
      name: esp32-uc2-standalone-4
      version: v2026.0.0-beta.3
    manufacturer: openUC2
    name: UC2-Mainboard-v4
    protocol: uc2-rest
    type: controller
    uc2-rest:
      serial:
        baudrate: 115200
        device-pattern: /dev/ttyUSB*
      transport: serial
newswitch-version: v0.1.0-alpha.0
