newswitch-version: v0.1.0-alpha.0
devices:
  laser:
    kind: source
    source:
      kind: laser
      laser:
        wavelength: 485 # nm
    controller: mainboard
  hikcam:
    kind: detector
    detector:
      rgb: true
      dimensions: # in pixels
        width: 1000
        height: 1000
  mainboard:
    kind: microcontroller
    microcontroller:
      protocol: uc2-rest # can be uc2-rest or can-open
      uc2-rest:
        transport: serial # can be serial or HTTP
        serial:
          device-pattern: '/dev/ttyUSB*'
          baudrate: 115200
      firmware:
        name: esp32-uc2-standalone-4
        version: v2026.0.0-beta.3
  stage:
    kind: stage
    stage:
      kind: orthogonal-xyz
      orthogonal-xyz:
        devices:
          x-actuator: stage-x
          x-limit: null
          y-actuator: stage-y
          y-limit: null
          z-actuator: stage-z
          z-limit: null
  stage-x:
    kind: actuator
    actuator:
      kind: linear
      linear:
        min: 0 # mm
        max: 25 # mm
    controller: mainboard
    optikit:
      dsn-input-variable: sample-x
  stage-y:
    kind: actuator
    actuator:
      kind: linear
      linear:
        min: 0 # mm
        max: 25 # mm
    controller: mainboard
    optikit:
      dsn-input-variable: sample-y
  stage-z:
    kind: actuator
    actuator:
      kind: linear
      linear:
        min: 0 # mm
        max: 25 # mm
    controller: mainboard
    optikit:
      dsn-input-variable: sample-z
